package ch.epfl.sweng.radin.databases;

public class DatabaseFactory {
	private static final String CREATE_USER_TABLE = "CREATE TABLE USER_RELATIONSHIP(_UID_SOURCE INT NOT NULL,"
			+ "_UID_TARGET INT NOT NULL,"
			+ "RELATION INT NOT NULL,"
			+ "FOREIGN KEY (_UID_SOURCE, _UID_TARGET), REFERENCES USER(_UID, _UID),"
			+ "PRIMARY KEY (_UID_SOURCE, _UID_TARGET));";
	private static final String CREATE_MEMBER_TABLE = "CREATE TABLE MEMBER_IN_RADIN("
			+ "_UID INT NOT NULL,"
			+ "_RID INT NOT NULL,"
			+ "START_DATE TEXT NOT NULL,"
			+ "PERMISSION INT NOT NULL,"
			+ "DELETED_AT TEXT,"
			+ "FOREIGN KEY (_UID) REFERENCES USER(_UID),"
			+ "FOREIGN KEY (_RID) REFERENCES RADIN_GROUP(_RID),"
			+ "PRIMARY KEY (_UID, _RID));";
	private static final String CREATE_USER_CONCERNED_BY_TRANSACTION_TABLE = "CREATE TABLE USER_CONCERNED_BY_TRANSACTION(\r\n" + 
			"_TID INT NOT NULL," + 
			"_UID INT NOT NULL," + 
			"COEFFICIENT INT NOT NULL," + 
			"FOREIGN KEY (_TID) REFERENCES TRANSACTION(_TID)," + 
			"FOREIGN KEY (_UID) REFERENCES USER(_UID)," + 
			"PRIMARY KEY (_TID, _UID)" + 
			");";
}
